apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 9000
  type: {{ .Values.service.type }}