replicaCount: 1
image:
  repository: my-registry.local:5000/my-service
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 9000
ingress:
  enabled: true
  host: my-service.local
